### ISSUE TITLE
Google Adsense is incorrectly listed as "does not" support SSL

### ISSUE THREAD

**Issue by jaxley** [andrewhilts/trackerssl#10]
Per https://support.google.com/adsense/answer/10528?hl=en, you can use SSL for Google AdSense.  The current tracker SSL extension still shows them as not supporting SSL though.

Could you perhaps link to more information about why each tracker is listed as supporting/not supporting SSL for reference and posterity?  Would be helpful to validate the information.

I presume that if something is listed as "does not" support, that means _confirmed_ to not support SSL vs. unconfirmed?

**Comment by andrewhilts** [comment]
Hi there,

Apologies for the delay in getting back to you.

If you saw something like the below for Google, (alongside the opened lock icon), then TrackerSSL is telling you that the Google hostname in question _could_ be sending tracking data securely, but the website embedding the Google tracker is using an http-only url scheme, rendering any additional transit security meaningless for the transmission in question. I hope this helps, let me know if I misunderstood you.

![image](https://cloud.githubusercontent.com/assets/701952/9445175/ba1e3798-4a58-11e5-870b-99cc936cb944.png)

**Comment by jaxley** [comment]
I would not rule out misreading the notice, but I'm pretty sure I saw google ad services show up as "does not" support secure transmission.  I went to pull it again but the site in question has now changed to HTTPS by default so I can't reproduce it.  Close it for now and I'll reopen if I see it show up again.
